name: 'Deployment for iOS'

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    needs: run-tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        if: ${{ inputs.run-tests }}
        run: flutter test

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/ci-cd-apps

      - run: mv Runner.app/ Payload
        working-directory: build/ios/ci-cd-apps

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/ci-cd-apps

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ci-cd-apps/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "IPA App Created!"
