name: 'Deployment for iOS'

on:
  push:
    branches: [ ios-version ]

jobs:
  run-tests:
    uses: ./.github/workflows/common.yml
    with:
      run-tests: true

  build-ios:
    needs: run-tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "IPA App Created!"
