name: 'Deployment for Android'

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    uses: ./.github/workflows/common.yml
    with:
      run-tests: true

  build-android:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
