name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: flutter pub get
        env:
          PUB_HOSTED_URL: https://pub.dev
          FLUTTER_STORAGE_BASE_URL: https://storage.googleapis.com

      - name: Run tests
        run: flutter test

      # I don't intend to build APK or publish to any store
      # - name: Build APK (optional)
      #   run: flutter build apk --release
